### ISSUE TITLE
How about making it "watch" for changes

### ISSUE THREAD

**Issue by tomdee** [dersimn/OpwnWRT-Presence-Detector-over-MQTT#1]
Something like I describe here for Amazon Dash buttons - http://www.tomdee.co.uk/2016/11/07/triggering-philips-hue-lights-using-amazon-dash-and-openwrt/

**Comment by dersimn** [comment]
I've already thought about making this event-based, but never came to dig deeper into that.
Thanks for the hint on your blog.

**Comment by dersimn** [comment]
Thanks for hint again.
