### ISSUE TITLE
No MQTT publications after upgrade to "presence_report"

### ISSUE THREAD

**Issue by zuernc** [dersimn/OpwnWRT-Presence-Detector-over-MQTT#11]
After upgrading from "presence_event.sh" and "presence_lastseen.sh" to the latest script MQTT publication of MAC addresses stopped working.

Inserted my MQTT-Servers IP in "presence_report", did `chmod x+u` the script and changed rc.local according to readme. 

Any idea what I'm missing? Do I need to make some other changes to the "presence_report" script?

Sorry to bother you again and thanks for your help!

**Comment by dersimn** [comment]
You don't need to edit the file anymore, just copy over the file from Git and specify the IP in rc.local (replace `192.168.1.2` with the IP of your MQTT broker):

```
nohup /usr/bin/presence_report event 192.168.1.2 >/dev/null 2>&1 &
nohup /usr/bin/presence_report lastseen 192.168.1.2 >/dev/null 2>&1 &
```

**Comment by zuernc** [comment]
Perfect, thanks again!
