### ISSUE TITLE
OH items: move to mqtt-v2 (OH 2.4+) binding

### ISSUE THREAD

**Issue by gsantner** [dersimn/OpwnWRT-Presence-Detector-over-MQTT#12]
OpenHab MQTT bindings seem to not work anymore, even with the v1 legacy binding installed.

There is a new binding available now, needs quite some changes: <https://www.openhab.org/blog/2018-12-16-mqtt-arrives-in-the-modern-openhab-2-x-architecture.html>

 If somebody did already move over to the new format, or plan todo so - please leave a message here which files you created with which content :)

**Comment by zuernc** [comment]
After installing the openHAB MQTT 2.4 binding:

1. change presence.item
```
//DateTime Person_1_Wifi_LastSeen "Person 1 Wifi last seen [%1$td.%1$tm.%1$tY %1$tH:%1$tM]" { mqtt="<[broker:owrtwifi/status/mac-xx-xx-xx-xx-xx-xx/lastseen/iso8601:state:default]" }
DateTime Person_1_Wifi_LastSeen "Person 1 Wifi last seen [%1$td.%1$tm.%1$tY %1$tH:%1$tM]" { channel="mqtt:topic:mosquitto:Person_1_Wifi_LastSeen" }
```

```
//Number   Person_1_Wifi_LastSeen_Seconds "Person 1 Wifi last seen [%d]" { mqtt="<[broker:owrtwifi/status/mac-xx-xx-xx-xx-xx-xx/lastseen/epoch:state:default]" }
Number   Person_1_Wifi_LastSeen_Seconds "Person 1 Wifi last seen [%d]" { channel="mqtt:topic:mosquitto:Person_1_Wifi_LastSeen_Seconds" }

```
2.  create a new item in PaperUI (i.e. Anwesenheit) and insert the "old" MQTT state topic
<img width="925" alt="Screenshot 2019-04-20 at 09 03 01" src="https://user-images.githubusercontent.com/31471604/56454117-700bda00-634c-11e9-9505-13fbae793963.png">

3. link the channel(s) from presence.item to the created item
<img width="856" alt="Screenshot 2019-04-20 at 09 03 34" src="https://user-images.githubusercontent.com/31471604/56454160-00e2b580-634d-11e9-9bea-c0f5a9c5ddc5.png">

The other channels can be linked accordingly to the same item. Enjoy ;)

**Comment by gsantner** [comment]
Thanks for help!

Can the whole graphical paperui configuration also be done instead by pure textual config?

**Comment by zuernc** [comment]
Yes, purely file based configuration is possible. There are several tutorials in the openHAB Community, i.e.:
[https://community.openhab.org/t/sonoff-tasmota-with-mqtt-binding-2-4-using-config-files/61494](url)

**Comment by dersimn** [comment]
I switched from OpenHAB to mqtt-smarthome a while ago, so.. just give me a PR once you got a working example😄

**Comment by zuernc** [comment]
Just proposed my examples.. hopefully! First time using git in that way ;)

**Comment by gsantner** [comment]
I uninstalled and reinstalled the mqtt (both new and legacy) binding multiple times, did multiple openhab restarts and then the code from this repository worked magically.

So yes you can upgrade it to new bindings, but the old one does still work for now.
