### ISSUE TITLE
mqtt user and password

### ISSUE THREAD

**Issue by jonathannpayne** [dersimn/OpwnWRT-Presence-Detector-over-MQTT#16]
Hi how can i configure the password and username for connecting to my mqtt server?

**Comment by cirolaferrara** [comment]
See https://github.com/dersimn/owrtwifi2mqtt/pull/18

**Comment by jonathannpayne** [comment]
that worked beautifully! i had been using the script with the dodgy hack of manually adding -u and -p to the publsh line but this is much more elegant! i have a new issue! i want to run this script and one that publishes the arp-cache and dhcp-cache but apparently only one will run and publish so i cant have them both at the same time! is there a work around?

**Comment by jonathannpayne** [comment]
That worked beautifully! many thanks
