### ISSUE TITLE
Subscription not working, please help troubleshooting 

### ISSUE THREAD

**Issue by zuernc** [dersimn/OpwnWRT-Presence-Detector-over-MQTT#4]
Sorry, very new to MQTT. 

I followed your instructions and everything seems to have worked fine: "mosquitto_sub -t '$SYS/#' -v" shows traffic.

Simple MQTT-sub/pub-trials work in Shell and MQTTLens but I can't get neither to receive messages when I subscribe to "owrtwifi/status/mac-[Devices-MAC-address]/lastseen".

Any idea what I'm doing wrong? Do I need to make changes to "presence_event.sh" and "presence_lastseen.sh" besides setting my MQTT-Servers IP?

Thanks for your help!

**Comment by dersimn** [comment]
Try subscribing to `owrtwifi/status/#`.
I just noticed, that I forgot to change the README file for the new topic name.

**Comment by zuernc** [comment]
Still nothing.. odd. I will skim through the whole setup again and see if I did something wrong.

Is there a way to monitor the provided scripts?

**Comment by dersimn** [comment]
Try to execute the last seen script manually via SSH, that should send some data via mqtt. Did you `chmod +x` the scripts after copying?

**Comment by zuernc** [comment]
`chmod +x` That did the trick! Thank you so much!
